core/base: Fix inconsistent use of tabs and spaces in indentation
The mixed use of space and tabs in the indentation causes TabError when importing the module.

Error: TabError: inconsistent use of tabs and spaces in indentation

Signed-off-by: Gegham Zakaryan <zakaryan.2004@outlook.com>